CREATE TABLE IF NOT EXISTS depth (
  id INT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  layer INT NOT NULL,
  side VARCHAR(255) NOT NULL,
  price NUMERIC NOT NULL,
  vol NUMERIC NOT NULL,
  FOREIGN KEY (id) REFERENCES orderbook(id)
)