# Use the official TimescaleDB image as a parent image
FROM timescale/timescaledb:latest-pg12

# (Optional) Add custom configurations or scripts
# COPY ./custom-config.conf /etc/timescaledb.conf

# Set environment variables if necessary
ENV POSTGRES_DB=cryptostream
ENV POSTGRES_USER=bullionbear
ENV POSTGRES_PASSWORD=Sunshine4Jellybean